Repository Solvro/web-solvro-docs, pull requests merged in 2025-09, with the labels that each got.

#97 fix: update repository links for eventownik
  src/content/docs/projects/Eventownik/Handbook.mdx
Labels: size/S

#96 feat(wakacyjne wyzwanie): web scraping and background processes
  src/content/docs/sections/Backend/Od zera do backend developera/scrapowanie-i-procesy-w-tle.mdx
Labels: documentation, size/XL

#92 feat: update head of promo 25 26
  src/content/docs/solvro/VIII_Board.mdx
Labels: size/XS
