Repository Solvro/web-solvro-docs, pull requests merged in 2025-03, with the labels that each got.

#42 Feat/recruitment process
  src/content/docs/sections/Management/Rekrutacja.mdx
Labels: documentation, size/L

#51 P005 K001 - Dodanie kontroli planu strategicznego i taktycznego
  src/content/docs/solvro/Statute.mdx
Labels: kontrproposal, size/XS

#48 P005 - Kolektywna kontrola zarządu
  src/content/docs/solvro/Statute.mdx
Labels: proposal, size/S

#45 P004 - Doprecyzowanie przekazanie władzy
  src/content/docs/solvro/Statute.mdx
Labels: proposal

#44 P003 Lex Olcia
  src/content/docs/solvro/Statute.mdx
Labels: proposal

#38 P001 - Ustanowienie sekcji
  src/content/docs/solvro/Statute.mdx
Labels: proposal, size/M

#37 P000 - Podstawa regulaminu
  .github/PULL_REQUEST_TEMPLATE.md
Labels: proposal, size/L

#53 fix: statute enumeration
  src/content/docs/solvro/Statute.mdx
Labels: size/XS

#52 feat: add botland order guide
  src/assets/hardware/zamowienia/adres-faktury.png
  src/assets/hardware/zamowienia/dodane-adresy.png
  src/assets/hardware/zamowienia/koszyk.png
  src/content/docs/sections/Hardware/About.md
  src/content/docs/sections/Hardware/bootland-order.md
Labels: size/M

#50 feat: basic info about client and server components + prisma
  src/assets/tutorials/nextjs/prisma-studio.png
  src/content/docs/sections/Frontend/Poradniki/Next.js/Komponenty Klienckie/client-components.mdx
  src/content/docs/sections/Frontend/Poradniki/Next.js/Komponenty Klienckie/next-hooks-and-other-packages.mdx
  src/content/docs/sections/Frontend/Poradniki/Next.js/Komponenty Serwerowe/database-connection.mdx
  src/content/docs/sections/Frontend/Poradniki/Next.js/Komponenty Serwerowe/prisma-queries.mdx
  src/content/docs/sections/Frontend/Poradniki/Next.js/Komponenty Serwerowe/server-components.mdx
  src/content/docs/sections/Frontend/Poradniki/Next.js/intro.mdx
  src/content/docs/sections/Frontend/Poradniki/feedback-form.mdx
Labels: size/XL

#49 feat: rest api and autoswagger tutorial
  src/content/docs/sections/Backend/API.md
Labels: documentation, size/L

#60 feat: add backend section in index
  src/content/docs/index.mdx
Labels: size/XS

#58 feat/kurs podstawy gita
  src/assets/tutorials/git-basics/git-3-branches.png
  src/assets/tutorials/git-basics/git-conflict-example.png
  src/assets/tutorials/git-basics/git-merge-squash-example.png
  src/assets/tutorials/git-basics/git-rebase-example.png
  src/assets/tutorials/git-basics/merge-squash-example.png
  src/assets/tutorials/git-basics/multi-branch-ex.png
  src/assets/tutorials/git-basics/one-branch-ex.png
  src/assets/tutorials/git-basics/pull-request-1.png
  src/assets/tutorials/git-basics/pull-request-2.png
  src/assets/tutorials/git-basics/solvro-git-logo.png
  src/content/docs/solvro/git-basics/git.mdx
  src/content/docs/solvro/git-basics/github.mdx
  src/content/docs/solvro/git-basics/intro.mdx
Labels: size/L
