Repository Solvro/web-solvro-docs, pull requests merged in 2025-04, with the labels that each got.

#65 fix/git-basics static images
  src/content/docs/solvro/git-basics/git.mdx
  src/content/docs/solvro/git-basics/github.mdx
  src/content/docs/solvro/git-basics/intro.mdx
Labels: size/M

#40 feat: first part of frontend roadmap
  src/content/docs/sections/Frontend/frontend-roadmap.md
Labels: size/L

#69 fix: links and typos
  src/content/docs/solvro/git-basics/github.mdx
  src/content/docs/solvro/git-basics/intro.mdx
Labels: size/S
